PUT  http://localhost:3000/modify
content-type: application/json




{
    
    "firstName": "Rudy",
    "lastName": "Hawtrey",
    "email": "rudy@gmail.com",
    "favorateColor": "Blue",
    "birthDay": "2-10-1975",
    "location": "Cape Town South Africa",
    "phoneNumber": "+27 68 055 1644",
    "companyName": "Forver Living Security"
  }